# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
  install:
    - requirements: requirements.txt
    - method: pip

# Build PDF & ePub
formats:
  - epub
  - pdf